# Generated by Django 4.2.1 on 2023-05-28 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('insignia', models.ImageField(upload_to='images/logros')),
                ('nivel', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado')])),
                ('requisitos', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
            },
        ),
        migrations.CreateModel(
            name='UserLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado')])),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.logro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userLogros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Logro',
                'verbose_name_plural': 'User Logros',
            },
        ),
        migrations.AddField(
            model_name='logro',
            name='owner',
            field=models.ManyToManyField(related_name='logros', through='achievements.UserLogro', to=settings.AUTH_USER_MODEL),
        ),
    ]
