# Generated by Django 4.2.1 on 2023-07-28 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAchievement',
            new_name='Award',
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Logro', 'verbose_name_plural': 'Logros'},
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'Premio', 'verbose_name_plural': 'Premios'},
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='bonus',
        ),
        migrations.AddField(
            model_name='achievement',
            name='criteria',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
