# Generated by Django 4.2.1 on 2023-07-28 21:52

import achievements.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_rename_userachievement_award_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge',
            field=models.FileField(null=True, upload_to='static/images/achievements', validators=[achievements.validators.validate_file_extension], verbose_name='Image'),
        ),
    ]
