# Generated by Django 4.2.1 on 2023-07-28 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodoro',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
