# Generated by Django 4.2.1 on 2023-07-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_alter_pomodoro_options_pomodoro_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('is_running', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='pomodoro',
            name='user',
        ),
    ]
