# Generated by Django 4.2.1 on 2023-07-28 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0006_timer_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
