# Generated by Django 4.2.1 on 2023-05-28 20:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField()),
                ('deadline', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('pe', 'Pendiente'), ('ep', 'En progreso'), ('co', 'Completado')], default='pe', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tiempo', models.DurationField(default=datetime.timedelta(days=25))),
                ('pausado', models.DurationField(default=datetime.timedelta(days=5))),
                ('total', models.DurationField(default=datetime.timedelta(0))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='subjects.tema')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['creado'],
            },
        ),
    ]
