# Generated by Django 4.2.1 on 2023-07-28 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='timer',
        ),
    ]
